version: '3.8'

services:
  web:
    build: .
    container_name: meu-apache-php
    ports:
      - "8080:80"
    volumes:
      - ./front:/var/www/html
    depends_on:
      - db
    networks:
      - minha-rede

  db:
    image: mysql:5.7
    container_name: meu-mysql
    environment:
      MYSQL_DATABASE: users
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - minha-rede

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
